export const NATIVE_TOOL_PREFIX = "gsv__";

export const NATIVE_TOOLS = {
  READ_FILE: `${NATIVE_TOOL_PREFIX}ReadFile`,
  WRITE_FILE: `${NATIVE_TOOL_PREFIX}WriteFile`,
  EDIT_FILE: `${NATIVE_TOOL_PREFIX}EditFile`,
  DELETE_FILE: `${NATIVE_TOOL_PREFIX}DeleteFile`,
  CONFIG_GET: `${NATIVE_TOOL_PREFIX}ConfigGet`,
  LOGS_GET: `${NATIVE_TOOL_PREFIX}LogsGet`,
  CRON: `${NATIVE_TOOL_PREFIX}Cron`,
  MESSAGE: `${NATIVE_TOOL_PREFIX}Message`,
  SESSIONS_LIST: `${NATIVE_TOOL_PREFIX}SessionsList`,
  SESSION_SEND: `${NATIVE_TOOL_PREFIX}SessionSend`,
} as const;
