/**
 * CLI Configuration Step
 * 
 * Saves the CLI config file so gsv commands work.
 */

import type { Prompter } from "../prompter";
import type { WizardState } from "../types";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import pc from "picocolors";

function getConfigDir(): string {
  const platform = os.platform();
  
  if (platform === "win32") {
    // Windows: %APPDATA%\gsv
    return path.join(process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming"), "gsv");
  }
  
  if (platform === "darwin") {
    // macOS: ~/Library/Application Support/gsv
    return path.join(os.homedir(), "Library", "Application Support", "gsv");
  }
  
  // Linux: XDG_CONFIG_HOME or ~/.config/gsv
  return process.env.XDG_CONFIG_HOME 
    ? path.join(process.env.XDG_CONFIG_HOME, "gsv")
    : path.join(os.homedir(), ".config", "gsv");
}

/**
 * Save CLI configuration file
 */
export async function saveCliConfig(
  p: Prompter,
  state: WizardState
): Promise<string> {
  const configDir = getConfigDir();
  const configPath = path.join(configDir, "config.toml");

  // Create config directory
  fs.mkdirSync(configDir, { recursive: true });

  // Build WebSocket URL from Gateway URL
  const gatewayUrl = state.deployment?.gatewayUrl || "https://gsv.example.workers.dev";
  const wsUrl = gatewayUrl
    .replace("https://", "wss://")
    .replace("http://", "ws://") + "/ws";

  const config = `# GSV CLI Configuration
# Generated by gsv-deploy wizard

[gateway]
url = "${wsUrl}"
token = "${state.authToken}"

[session]
default_key = "main"
`;

  fs.writeFileSync(configPath, config, "utf-8");
  p.success(`CLI config saved to ${pc.dim(configPath)}`);
  
  return configPath;
}
